# Generated by Django 2.1.5 on 2019-04-17 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_auto_20190413_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='house',
            name='bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='neighborhood',
            field=models.CharField(default='Toronto', max_length=100),
        ),
        migrations.AlterField(
            model_name='house',
            name='number_of_stories',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='property_type',
            field=models.CharField(default='Toronto', max_length=100),
        ),
        migrations.AlterField(
            model_name='house',
            name='sqft',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='house',
            name='year_built',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='houseimages',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='houses.House'),
        ),
    ]
