# Generated by Django 2.1.5 on 2019-04-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_auto_20190417_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='city',
            field=models.CharField(default='Calgary', max_length=100),
        ),
        migrations.AlterField(
            model_name='house',
            name='neighborhood',
            field=models.CharField(default='Parkdale', max_length=100),
        ),
        migrations.AlterField(
            model_name='house',
            name='property_type',
            field=models.CharField(default='Detached', max_length=100),
        ),
    ]
