# Generated by Django 2.1.5 on 2019-04-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0007_auto_20190417_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='house',
            name='img',
            field=models.CharField(default='no image', max_length=1000),
        ),
    ]
