# Generated by Django 2.1.5 on 2019-04-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='img',
            field=models.CharField(default='no image', max_length=300),
        ),
    ]
