# Generated by Django 2.1.5 on 2019-04-13 00:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_house_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='parking',
            new_name='basement',
        ),
        migrations.RemoveField(
            model_name='house',
            name='created_ad',
        ),
        migrations.AddField(
            model_name='house',
            name='city',
            field=models.CharField(default='Toronto', max_length=100),
        ),
        migrations.AddField(
            model_name='house',
            name='neighborhood',
            field=models.CharField(default='placeholder', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='number_of_stories',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='property_type',
            field=models.CharField(default='placeholder', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='sqft',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='year_built',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
