# Generated by Django 2.1.5 on 2019-04-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_auto_20190417_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseimages',
            name='images',
            field=models.TextField(default='no image', max_length=1000),
        ),
    ]
