# Generated by Django 2.1.5 on 2019-04-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0008_auto_20190419_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='img',
            field=models.CharField(default='no image', max_length=100000),
        ),
        migrations.AlterField(
            model_name='houseimages',
            name='images',
            field=models.TextField(default='no image', max_length=100000),
        ),
    ]
