# Generated by Django 2.2 on 2019-04-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0010_house_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
