# Generated by Django 2.2 on 2019-04-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0013_auto_20190425_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
